extends GcityTest

## The M6 replay fixtures (spec claim 15), generated by tools/make_m6_fixtures.gd: the
## mission played four ways as command logs, replayed headless. A fixture that only
## reproduced a hash would prove determinism and nothing else, so each one is replayed
## and then asked what actually happened in it.
##
## The site is raised by its operator in every fixture, so the player owns nothing and
## every entry is a break-in.

const QUEST: StringName = &"cold_storage"
const CURVE: StringName = &"fixer_standard"

var _sim: SimRoot
var _score: RunScoreSystem
var _quests: QuestSystem
var _items: ItemSystem
var _actors: ActorSystem
var _corpses: CorpseSystem
var _standing: StandingSystem
var _player: int = 0


## Replays a fixture and asserts its recorded hash, twice, so a fixture that stopped
## reproducing fails here as well as in the replay stage.
func _replay(name: String) -> void:
	var path: String = "res://tests/replay/%s.json" % name
	var fixture: ReplayFixture = ReplayFixture.parse(read_text(path))
	assert_true(fixture.is_valid(), "%s valid: %s" % [name, fixture.error])
	var db := ContentDb.new()
	assert_eq(ContentLoader.load_all(db), OK, "content")
	_sim = SimAssembly.build(fixture.seed, db)
	var hash: String = Replay.run(fixture, _sim)
	assert_eq(hash, fixture.expected_hash, "%s reproduces its recorded hash" % name)
	_score = SimAssembly.score_of(_sim)
	_quests = SimAssembly.quests_of(_sim)
	_items = SimAssembly.items_of(_sim)
	_actors = SimAssembly.actors_of(_sim)
	_corpses = SimAssembly.corpses_of(_sim)
	_standing = SimAssembly.standing_of(_sim)
	# the operator is spawned first and the player next; the site's guards are agents.
	# Since M7 claim 10 the player takes the contract before the building is raised, so
	# the guards come last: the player is the last actor that is not an agent
	var perception: PerceptionSystem = SimAssembly.perception_of(_sim)
	_player = 0
	for id: int in _actors.actor_ids():
		if id > _player and not perception.is_agent(id):
			_player = id
	assert_true(_player != 0, "%s: found the player" % name)


func test_the_stealth_run_is_clean_and_pays_the_bonus() -> void:
	_replay("m6-stealth")
	assert_eq(_score.counters(_player), [0, 0, 0, 0] as Array[int], "nobody saw, nobody heard, nobody died, nothing left")
	assert_true(_score.is_clean(_player), "a full stealth run")
	assert_eq(_score.multiplier(_player, CURVE), 2000, "and the clean bonus")
	assert_eq(_quests.status_of(_player, QUEST), QuestSystem.STATUS_COMPLETED, "the contract was handed in")
	assert_eq(_items.credits_in(ItemSystem.inventory_of(_player)), 2400, "paid double")
	assert_eq(_standing.heat_of(_player), 0, "and no heat: the grate was in a public street and went back")
	assert_false(_actors.is_alive(_player) == false, "the player walked away")


func test_the_loud_run_takes_the_data_anyway_and_pays_for_it() -> void:
	_replay("m6-loud")
	var counters: Array[int] = _score.counters(_player)
	assert_true(counters[0] > 0, "seen (%d times)" % counters[0])
	assert_true(counters[1] > 0, "and reported (%d alarms)" % counters[1])
	assert_true(counters[2] >= 1, "guards down (%d)" % counters[2])
	assert_true(counters[3] > 0, "and a mess left behind (%d traces)" % counters[3])
	assert_false(_score.is_clean(_player), "not a stealth run by any reading")
	assert_eq(_score.multiplier(_player, CURVE), 250, "the curve floors it")
	assert_eq(_quests.status_of(_player, QUEST), QuestSystem.STATUS_COMPLETED, "the data was taken anyway")
	assert_eq(_items.credits_in(ItemSystem.inventory_of(_player)), 300, "and paid at the floor")
	assert_true(_standing.heat_of(_player) > 1000, "heat raised (%d)" % _standing.heat_of(_player))


func test_the_death_run_leaves_a_body_and_the_recovery_run_gets_the_kit_back() -> void:
	_replay("m6-death")
	var corpse: int = _corpses.corpse_of(_player)
	assert_true(corpse != EntityIds.NONE, "the player died and left a body")
	assert_true(_actors.is_alive(_player), "and came back")
	assert_true(_corpses.is_stripped(corpse), "the body was emptied by the recovery run")
	assert_true(_items.items_in(ItemSystem.inventory_of(_player)).size() >= 4, "with the kit in the pocket again (%d items)" % _items.items_in(ItemSystem.inventory_of(_player)).size())
	assert_true(_corpses.has_corpse(corpse), "the body is still lying where it fell")
	# M7 claim 10: the building only stands somewhere because the contract was taken and
	# its handle bound, so the contract is on the books; it was never finished
	assert_eq(_quests.status_of(_player, QUEST), QuestSystem.STATUS_ACTIVE, "and the contract was taken but never finished")


func test_the_side_route_proves_vertical_movement_in_a_replay() -> void:
	_replay("m6-side")
	# the run goes up the outside fire stair, in at the maintenance window, across the
	# upper floor and down the inside flight: four level changes, none of them faked
	assert_eq(_score.counters(_player), [0, 0, 0, 0] as Array[int], "nobody saw it")
	var movement: MovementSystem = SimAssembly.movement_of(_sim)
	assert_eq(movement.fall_count(), 0, "and nothing fell: every level change was climbed")
	var ground_floor: int = SimAssembly.sites_of(_sim).cell_of(&"cold_storage", Vector3i(0, 1, 0)).y * BuildSystem.CELL
	assert_eq(_actors.position_of(_player).y, ground_floor, "ending on the ground floor, inside")
	assert_true(_actors.is_alive(_player), "unharmed")
