extends GcityTest

## The M5 replay fixtures (spec claim 15), generated by tools/make_m5_fixtures.gd:
## the device's own command streams replayed headless, so what the panes submit is
## proven without a window. Each is replayed tick by tick and its recorded hash
## asserted.

const PLAYER: int = 1

var _sim: SimRoot
var _items: ItemSystem
var _actors: ActorSystem
var _quests: QuestSystem
var _land: LandSystem
var _combat: CombatSystem
var _first_pause: int = -1
var _resumed_at: int = -1


func _replay(name: String) -> void:
	var path: String = "res://tests/replay/%s.json" % name
	var fixture: ReplayFixture = ReplayFixture.parse(read_text(path))
	assert_true(fixture.is_valid(), "%s valid: %s" % [name, fixture.error])
	var db := ContentDb.new()
	assert_eq(ContentLoader.load_all(db), OK, "content")
	_sim = SimAssembly.build(fixture.seed, db)
	_items = SimAssembly.items_of(_sim)
	_actors = SimAssembly.actors_of(_sim)
	_quests = SimAssembly.quests_of(_sim)
	_land = SimAssembly.land_of(_sim)
	_combat = SimAssembly.combat_of(_sim)
	for c: SimCommand in fixture.commands:
		assert_eq(_sim.submit(c), OK, "submit")
	_first_pause = -1
	_resumed_at = -1
	var was_paused: bool = false
	for i: int in fixture.ticks:
		var before: bool = _sim.is_paused()
		_sim.step()
		if _sim.is_paused() and _first_pause < 0:
			_first_pause = _sim.get_tick()
		if before and not _sim.is_paused() and _resumed_at < 0:
			_resumed_at = i
		was_paused = _sim.is_paused()
	assert_false(fixture.expected_hash.is_empty(), "%s has its hash recorded" % name)
	assert_eq(_sim.state_hash(), fixture.expected_hash, "%s matches the recorded hash" % name)


func _inv() -> StringName:
	return ItemSystem.inventory_of(PLAYER)


func _of_kind(kind: StringName) -> int:
	for id: int in _items.items_in(_inv()):
		if _items.item_kind(id) == kind:
			return id
	return 0


func test_inventory_the_panes_commands_carry_fit_load_wield_and_swap() -> void:
	_replay("m5-inventory")
	var device: int = _actors.device_of(PLAYER)
	assert_true(device > 0, "the handset is carried")
	assert_eq(_items.item_kind(device), ItemSystem.KIND_DEVICE_FRAME, "a device frame")
	assert_eq(_items.provides_of(device), [] as Array[StringName], "the module was fitted and taken out again")
	assert_eq(_items.socket_part(device, &"radio"), 0, "the bay is empty")
	var pistol: int = _of_kind(ItemSystem.KIND_FRAME)
	assert_eq(_actors.wielded(PLAYER), pistol, "the pistol is wielded")
	var mag: int = _items.magazine_of(pistol)
	assert_true(mag > 0, "a magazine is in it")
	assert_eq(_items.rounds_in(mag).size(), 14, "fifteen loaded, one chambered by the reload")
	assert_true(_items.chambered(pistol) > 0, "and the chamber is full")
	assert_eq(_sim.rejected_count(), 0, "every command the panes submitted was accepted")
	assert_false(_sim.is_paused(), "this stream never paused")


func test_quest_accept_three_hits_completed_and_the_reward_lands() -> void:
	_replay("m5-quest")
	assert_eq(_quests.status_of(PLAYER, &"first_blood"), QuestSystem.STATUS_COMPLETED, "completed")
	assert_eq(_quests.progress_of(PLAYER, &"first_blood"), [3] as Array[int], "three handgun hits counted, and no more")
	assert_eq(_quests.completed_count(), 1, "once")
	assert_true(_combat.hits() >= 3, "the dummy took them (%d hits of %d shots)" % [_combat.hits(), _combat.shots()])
	var rounds: int = 0
	for id: int in _items.items_in(_inv()):
		if _items.item_kind(id) == ItemSystem.KIND_AMMO:
			rounds += 1
	assert_eq(rounds, 20, "the reward's fifteen rounds, plus the five the stream never loaded")
	assert_true(_sim.rejected_count() > 0, "the stream fires a full magazine dry and then abandons a completed quest: those refusals are the point")


func test_pause_is_refused_off_the_plot_granted_at_home_and_freezes_the_world() -> void:
	_replay("m5-pause")
	assert_eq(_land.violation_count(), 1, "one land.violation: the pause attempted off the plot")
	assert_eq(_sim.rejected_count(), 1, "that one command was refused; nothing else was")
	assert_true(_first_pause > 0, "the pause at home was granted (tick %d)" % _first_pause)
	assert_true(_resumed_at >= 0, "and the resume let the world run again (step %d)" % _resumed_at)
	var device: int = _actors.device_of(PLAYER)
	assert_eq(_items.provides_of(device), [&"radio"] as Array[StringName], "the module fitted on the frozen step")
	var pistol: int = _of_kind(ItemSystem.KIND_FRAME)
	assert_true(_items.magazine_of(pistol) > 0, "and the reload ran once the world was running again")
	var _home_x: int = _actors.position_of(PLAYER).x
	assert_true(_sim.is_paused(), "the stream ends with the device raised: still frozen")
	assert_true(_sim.paused_steps() > 100, "for a hundred frozen steps and more (%d)" % _sim.paused_steps())
	var tick_at_end: int = _sim.get_tick()
	_sim.step_n(50)
	assert_eq(_sim.get_tick(), tick_at_end, "the tick does not move while it stays raised")
	assert_eq(_actors.position_of(PLAYER).x, _home_x, "and the step queued behind the pause never happened")
