extends GcityTest

## The M7 replay fixtures (spec claim 17), generated by tools/make_m7_fixtures.gd. A
## fixture that only reproduced a hash would prove determinism and nothing else, so each
## one is replayed and then asked what actually happened in it. The two that are about
## something passing — a squad coming and going, a player through the gate and back —
## are replayed a tick at a time and watched on the way.

const QUEST: StringName = &"cold_storage"

var _sim: SimRoot
var _fixture: ReplayFixture


func _load(name: String) -> void:
	var path: String = "res://tests/replay/%s.json" % name
	_fixture = ReplayFixture.parse(read_text(path))
	assert_true(_fixture.is_valid(), "%s valid: %s" % [name, _fixture.error])
	var db := ContentDb.new()
	assert_eq(ContentLoader.load_all(db), OK, "content")
	_sim = SimAssembly.build(_fixture.seed, db)


## Replays a fixture and asserts its recorded hash.
func _replay(name: String) -> void:
	_load(name)
	assert_eq(Replay.run(_fixture, _sim), _fixture.expected_hash, "%s reproduces its recorded hash" % name)


## Replays a fixture a tick at a time, calling `watch` after every tick, and asserts the
## recorded hash at the end: the same run [Replay.run] makes, only looked at on the way.
func _replay_watching(name: String, watch: Callable) -> void:
	_load(name)
	for command: SimCommand in _fixture.commands:
		assert_eq(_sim.submit(command), OK, "%s: %s at tick %d submits" % [name, command.kind, command.tick])
	for i: int in _fixture.ticks:
		_sim.step()
		watch.call()
	assert_eq(_sim.state_hash(), _fixture.expected_hash, "%s reproduces its recorded hash" % name)


func _player() -> int:
	var actors: ActorSystem = SimAssembly.actors_of(_sim)
	var perception: PerceptionSystem = SimAssembly.perception_of(_sim)
	for id: int in actors.actor_ids():
		if not perception.is_agent(id):
			return id
	return EntityIds.NONE


func _region_of(actor: int) -> StringName:
	var at: Vector3i = SimAssembly.actors_of(_sim).position_of(actor)
	return SimAssembly.regions_of(_sim).region_at(at.x, at.z).id()


func test_the_graph_fixture_is_the_world_its_seed_generates() -> void:
	_replay("m7-graph")
	var routes: RouteGraph = SimAssembly.routes_of(_sim)
	assert_eq(routes.world_seed(), _fixture.seed, "the world is the fixture's seed")
	var again := RouteGraph.new()
	again.set_kits(SettlementKits.prepared(SimAssembly.content_of(_sim)))
	again.generate(_fixture.seed)
	assert_eq(again.world_hash(), routes.world_hash(), "and generating it again gives the same world")
	assert_true(routes.everywhere_is_reachable(), "a world every place of which is reachable")
	assert_true(routes.town_count() > 0 and routes.slot_count() > 0, "with towns (%d) and slots (%d)" % [routes.town_count(), routes.slot_count()])


func test_the_bind_fixture_takes_a_contract_and_binds_a_place() -> void:
	_replay("m7-bind")
	var binder: SiteBinder = SimAssembly.binder_of(_sim)
	var routes: RouteGraph = SimAssembly.routes_of(_sim)
	var slot: int = binder.slot_of(QUEST)
	assert_true(slot != EntityIds.NONE, "the contract bound a slot")
	assert_true(binder.is_bound(slot), "and the slot is taken")
	assert_eq(binder.bound_quests(), [QUEST] as Array[StringName], "by that contract alone")
	var node: int = binder.node_of(QUEST)
	assert_eq(routes.kind_of(node), RouteGraph.KIND_SITE, "a site node on the graph")
	assert_true(routes.path_between(1, node).size() >= 2, "that the road from the gate reaches")
	assert_eq(SimAssembly.quests_of(_sim).status_of(_player(), QUEST), QuestSystem.STATUS_ACTIVE, "and the contract is on the books")


func test_the_hydrate_fixture_brings_a_squad_in_walks_it_and_lets_it_go() -> void:
	_replay_watching("m7-hydrate", _watch_squad)
	var tokens: MacroTokenSystem = SimAssembly.tokens_of(_sim)
	assert_eq(tokens.token_ids().size(), 1, "one token")
	var token: int = tokens.token_ids()[0]
	assert_true(_came != -1, "the squad came in")
	assert_eq(_members, 3, "three of them")
	assert_true(_walked_mm > 100_000, "walked the road itself (%d mm)" % _walked_mm)
	assert_true(_went > _came, "and went back to being a token (in %d, out %d)" % [_came, _went])
	assert_false(tokens.is_held(token), "which walks on by itself")
	assert_eq(tokens.payload_of(token)["members"], 3, "all three still in it")
	assert_eq(SimAssembly.actors_of(_sim).actor_ids(), [_player()] as Array[int], "and nobody is left standing about")


func test_the_seam_fixture_goes_through_the_gate_and_back() -> void:
	_replay_watching("m7-seam", _watch_player)
	var player: int = _player()
	assert_true(_saw_transit, "the gate was taken with its load window")
	assert_true(_saw_wilds, "the player was out in the wilds")
	assert_eq(_region_of(player), &"city", "and is home again")
	assert_false(SimAssembly.regions_of(_sim).in_transit(player), "all the way through")
	assert_true(SimAssembly.actors_of(_sim).is_alive(player), "unharmed")
	assert_true(SimAssembly.regions_of(_sim).ground_revision() > 0, "and the ground dug out there is part of the state")


# ---------------------------------------------------------------- watching

## What the hydrate fixture's squad did: the tick it came in and went, how many it was,
## and how far its lead got from where it appeared.
var _came: int = -1
var _went: int = -1
var _members: int = 0
var _from: Vector3i = Vector3i.ZERO
var _walked_mm: int = 0
## What the seam fixture's player did.
var _saw_transit: bool = false
var _saw_wilds: bool = false


func _watch_squad() -> void:
	var hydration: HydrationSystem = SimAssembly.hydration_of(_sim)
	var tokens: MacroTokenSystem = SimAssembly.tokens_of(_sim)
	if tokens.token_ids().is_empty():
		return
	var token: int = tokens.token_ids()[0]
	if not hydration.is_hydrated(token):
		if _came != -1 and _went == -1:
			_went = _sim.get_tick()
		return
	var lead: Vector3i = SimAssembly.actors_of(_sim).position_of(hydration.members_of(token)[0])
	if _came == -1:
		_came = _sim.get_tick()
		_members = hydration.members_of(token).size()
		_from = lead
	_walked_mm = maxi(_walked_mm, PerceptionSystem.distance_mm(_from, lead))


func _watch_player() -> void:
	var player: int = _player()
	if player == EntityIds.NONE:
		return
	_saw_transit = _saw_transit or SimAssembly.regions_of(_sim).in_transit(player)
	_saw_wilds = _saw_wilds or _region_of(player) == &"wilds"
